import type { NextPage } from 'next'
import Head from 'next/head'

import { Layout } from '../components/Layout'
import { Header } from '../components/Header'
import { Main } from '../components/Main'
import { Footer } from '../components/Footer'
import { PokeCard } from '../components/PokeCard'
import { Loader } from '../components/Loader'

import { setPokemonTypeColor } from '../utils/setPokemonTypeColor'

import mock from '../mock/pokemon.json'
const arr = [mock, mock, mock, mock, mock, mock, mock, mock, mock, mock, mock, mock, mock, mock, mock, mock, mock]

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/static/favicon.ico" />
      </Head>
      <Header />
      <Main>
        {/*TODO: Implementar o consumo da api*/}
        {/*TODO: Implementar lógica de loading*/}
        {/* <Loader loadingMessage='Carregando' /> */}

        {arr.map((pokemon, index) => {

          return (
            <PokeCard
              name={pokemon.name}
              id={pokemon.id}
              img={pokemon.img}
              type1={pokemon.type1}
              type2={pokemon.type2}
              typeColor1={setPokemonTypeColor(pokemon.type1)}
              typeColor2={setPokemonTypeColor(pokemon.type2)}
              status={pokemon.status}
              key={index}
            />
          )
        })}
      </Main>
      <Footer />
    </Layout>
  )
}

export default Home
